import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <div>
      <Toaster position="top-right"/>
      {children}
    </div>
  )
}
