export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <div 
    className="min-h-screen bg-cover bg-center bg-no-repeat"
      style={{
        backgroundImage: "url('/background_img.png')",
      }}
    >
      {children}
    </div>
  )
}
