import { Schibsted_Grotesk } from "next/font/google"
import "../style/globals.css";
import "../style/custom.css";

const schibstedGrotesk = Schibsted_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-schibsted",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${schibstedGrotesk.variable} font-schibsted`}>
        {children}
      </body>
    </html>
  );
}
